# Generated by Django 4.1.4 on 2023-02-09 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_rename_message_comment_rename_room_museum'),
    ]

    operations = [
        migrations.AddField(
            model_name='museum',
            name='avg_rating',
            field=models.IntegerField(default=0),
        ),
    ]
